### PR TITLE
Update to analytics-java 1.0.4

### PR DESCRIPTION
**Pull request by jmelching**
- update README
- remove callback functionality
- switch over to using Config vs. Options for the AnalyticsClient

### CODE REVIEW

**Comment by ebaxt** [comment]
Thanks for the PR. I'm curious to why you decided to removed the callback functionality, won't this be a breaking api-change?

**Comment by jmelching** [comment]
Callbacks have been removed from the latest Java api as far as I can tell.  I can leave it in but it doesn't seem to make sense anymore. So yes it's a breaking change and why I updated the version too.

**Comment by mveytsman** [comment]
I'm looking to send data to intercom, which requires "secure mode" https://segment.com/docs/integrations/intercom/#secure-mode

It looks like this library doesn't support sending the integrations hash, but  this PR is a step of the way there.

Any word on this?

**Comment by ebaxt** [comment]
@mveytsman New version deployed to clojars: https://clojars.org/analytics-clj
@jmelching Thanks for the PR, sorry it took so long to merge (totally forgot about it).

**Pull request merged**
